drop table if exists customers;

create table customers(
    id integer primary key generated by default as identity,
    name text,
    phone varchar(30)
);

insert into customers
    (name, phone)
    values 
    ('Sam', '123-4566'),
    ('Hero', '123-3241'),
    ('Ram', '1233-1231');