BEGIN;

-- Creating supplier table
DROP TABLE IF EXISTS supplier;

CREATE TABLE supplier(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_name TEXT NOT NULL,
    phone TEXT,
    city TEXT
);


-- Creating Items Table with supplier as the foreign key
DROP TABLE IF EXISTS item;

CREATE TABLE item(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    unit TEXT,
    unit_cost NUMERIC, 
    supplier INTEGER REFERENCES supplier(id) NOT NULL
);


-- Creating Supplier Order table with item as the foreign key
DROP TABLE IF EXISTS supplier_order;

CREATE TABLE supplier_order(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE DEFAULT NOW(),
    item INTEGER REFERENCES item(id) NOT NULL,
    amount NUMERIC,
    total_cost NUMERIC,
    shipping_status TEXT
);

COMMIT;