BEGIN;

-- DROP TABLES in order so the foriegn keys dont affect the drop
DROP TABLE IF EXISTS supplier_order;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS supplier;

-- Creating supplier table
CREATE TABLE supplier(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_name TEXT NOT NULL,
    phone TEXT,
    city TEXT
);


-- Creating Items Table with supplier as the foreign key
CREATE TABLE item(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    unit TEXT,
    unit_cost NUMERIC, 
    supplier INTEGER REFERENCES supplier(id) ON DELETE SET NULL
);


-- Creating Supplier Order table with item as the foreign key
CREATE TABLE supplier_order(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE DEFAULT NOW(),
    item INTEGER REFERENCES item(id) ON DELETE CASCADE NOT NULL,
    amount NUMERIC,
    total_cost NUMERIC,
    shipping_status TEXT
);

COMMIT;